apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-deployment
spec:
  selector:
    matchLabels:
      app: aplicacao-pod
  replicas: 1
  template:
    metadata:
      labels:
       app: aplicacao-pod
    spec:
      containers: 
      - name: container-aplicacao-loja
        image: rodrigorahman/php-server-projeto
        ports: 
          - containerPort: 80